server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: BialasSQL2115
    url: jdbc:mysql://mkwk107.cba.pl/domaba69
    username: domabaSQL
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
      show-sql: true